language: java

jdk:
  - oraclejdk8

before_install:
    - chmod +x gradlew

script: ./gradlew build jacocoTestReport

after_success: 
    - ./gradlew -d jacocoRootReport coveralls
    - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
